---
# Location of Net Logo install for RNetLogo
netlogo-path: "C:/Program Files/NetLogo 6.0/app"

# R executable path
# - Used by SyncroSim in the coupled model
# - Rstudio can be used in place of RScript for debugging
R-executable-path: "C:/Program Files/R/R-4.0.3/bin/Rscript.exe"

# Run controls
max-years: 30
max-iterations: 40
max-jobs: 8
